<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReliefManagementSystem.Domain\ReliefManagementSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <EmbeddedResource Remove="Tests\**\*" />
    <None Remove="Tests\**\*" />
    <Content Remove="Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Interface\" />
    <Folder Include="Features\Auth\Service\" />
    <Folder Include="Features\Inventory\DTOs\" />
    <Folder Include="Features\Inventory\Interface\" />
    <Folder Include="Features\Inventory\Service\" />
    <Folder Include="Features\TeamJoinRequest\Interface\" />
    <Folder Include="Features\TeamJoinRequest\Service\" />
    <Folder Include="Features\Team\Interface\" />
    <Folder Include="Features\Team\Service\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
  </ItemGroup>

</Project>
