using Microsoft.Extensions.Options;
using ReliefManagementSystem.Application.Common.Interface;
using ReliefManagementSystem.Application.Common.Models;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

namespace ReliefManagementSystem.Infrastructure.DisasterAnalysis
{
    public class OpenAiCompatibleLlmAnalysisService : ILlmAnalysisService
    {
        private const string PromptVersion = "disaster-analysis-v1";

        private readonly HttpClient _httpClient;
        private readonly LlmProviderSettings _settings;

        public OpenAiCompatibleLlmAnalysisService(HttpClient httpClient, IOptions<LlmProviderSettings> options)
        {
            _httpClient = httpClient;
            _settings = options.Value;

            if (!string.IsNullOrWhiteSpace(_settings.BaseUrl) && _httpClient.BaseAddress == null)
            {
                _httpClient.BaseAddress = new Uri(_settings.BaseUrl.TrimEnd('/') + "/");
            }

            if (!string.IsNullOrWhiteSpace(_settings.ApiKey))
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _settings.ApiKey);
            }
        }

        public async Task<LlmDisasterAnalysisResult> AnalyzeRiskAsync(
            DisasterRiskAssessment primaryAssessment,
            IReadOnlyCollection<DisasterRiskAssessment>? rankedAssessments = null,
            string? requestedModel = null,
            CancellationToken cancellationToken = default)
        {
            var model = !string.IsNullOrWhiteSpace(requestedModel)
                ? requestedModel.Trim()
                : _settings.DefaultModel;

            if (string.IsNullOrWhiteSpace(_settings.ApiKey))
            {
                throw new InvalidOperationException("LlmProvider:ApiKey is missing.");
            }

            if (string.IsNullOrWhiteSpace(model))
            {
                throw new InvalidOperationException("No LLM model was provided. Set LlmProvider:DefaultModel or pass request.model.");
            }

            var payload = new
            {
                model,
                temperature = _settings.Temperature,
                max_tokens = _settings.MaxTokens,
                messages = new object[]
                {
                    new { role = "system", content = BuildSystemPrompt() },
                    new { role = "user", content = BuildUserPrompt(primaryAssessment, rankedAssessments) }
                }
            };

            using var response = await _httpClient.PostAsJsonAsync(
                NormalizePath(_settings.ChatCompletionsPath),
                payload,
                cancellationToken);

            var body = await response.Content.ReadAsStringAsync(cancellationToken);
            response.EnsureSuccessStatusCode();

            using var doc = JsonDocument.Parse(body);
            var content = ExtractAssistantContent(doc.RootElement);
            var jsonContent = ExtractJsonObject(content);

            var parsed = JsonSerializer.Deserialize<LlmJsonResponse>(jsonContent, JsonOptions())
                ?? throw new InvalidOperationException("LLM returned an empty JSON response.");

            return new LlmDisasterAnalysisResult
            {
                ProviderName = string.IsNullOrWhiteSpace(_settings.ProviderName) ? "OpenAI-Compatible" : _settings.ProviderName,
                ModelUsed = model,
                PromptVersion = PromptVersion,
                AnalyzedAt = DateTime.UtcNow,
                Summary = parsed.Summary ?? string.Empty,
                DetailedAnalysis = parsed.DetailedAnalysis ?? string.Empty,
                Recommendations = parsed.Recommendations ?? new List<string>(),
                PotentialScenarios = parsed.PotentialScenarios ?? new List<string>(),
                RawResponse = jsonContent
            };
        }

        private static string BuildSystemPrompt()
        {
            return """
You are a disaster risk analyst for a relief management system in Vietnam.
You receive structured weather data and a heuristic risk assessment generated by the system.

Your job:
1. Explain why the system assigned the current risk score and risk level.
2. Describe possible disaster scenarios relevant to the requested disaster type.
3. Provide 3-5 short, actionable recommendations for relief coordinators.

Rules:
- Never change, re-score, or contradict the provided risk score or risk level.
- Always answer in Vietnamese.
- Be careful, practical, and specific.
- If the disaster type is not directly predictable from weather data, clearly say that this is a weather-informed operational assessment, not a scientific event prediction.
- Return pure JSON only with this shape:
{
  "summary": "string",
  "detailedAnalysis": "string",
  "recommendations": ["string"],
  "potentialScenarios": ["string"]
}
""";
        }

        private static string BuildUserPrompt(
            DisasterRiskAssessment assessment,
            IReadOnlyCollection<DisasterRiskAssessment>? rankedAssessments = null)
        {
            var weather = assessment.WeatherSnapshot;
            var triggerFactors = assessment.TriggerFactors.Count == 0
                ? "- Không có yếu tố nổi bật"
                : string.Join("\n", assessment.TriggerFactors.Select(x => $"- {x}"));

            var scenarios = assessment.PotentialScenarios.Count == 0
                ? "- Chưa có"
                : string.Join("\n", assessment.PotentialScenarios.Select(x => $"- {x}"));

            var threats = assessment.TopThreats.Count == 0
                ? "- Chưa có"
                : string.Join("\n", assessment.TopThreats.Select(x => $"- {x}"));

            var note = string.IsNullOrWhiteSpace(assessment.DataLimitationNote)
                ? ""
                : $"\nLưu ý giới hạn dữ liệu: {assessment.DataLimitationNote}";

            var additionalContext = string.IsNullOrWhiteSpace(assessment.AdditionalContext)
                ? "Không có"
                : assessment.AdditionalContext;

            var ranking = rankedAssessments == null || rankedAssessments.Count == 0
                ? $"- {assessment.DisasterType}: {assessment.OverallRiskScore}/100 ({assessment.RiskLevel})"
                : string.Join("\n", rankedAssessments.Select(x =>
                    $"- {x.DisasterType}: {x.OverallRiskScore}/100 ({x.RiskLevel}), confidence {x.AssessmentConfidence}, triggers: {(x.TriggerFactors.Count == 0 ? "không có yếu tố nổi bật" : string.Join(", ", x.TriggerFactors))}"));

            return $"""
## Dữ liệu phân tích
- Khu vực: {assessment.LocationName}
- Nguy cơ nổi bật nhất do hệ thống xác định: {assessment.DisasterType}
- Bối cảnh bổ sung: {additionalContext}
- Điều kiện thời tiết: {weather.Condition}, nhiệt độ {weather.TemperatureC:0.##}°C, gió {weather.WindKph:0.##} km/h, mưa {weather.PrecipMm:0.##} mm, tầm nhìn {weather.VisibilityKm:0.##} km, độ ẩm {weather.Humidity}%
- Điểm rủi ro thời tiết cơ sở: {weather.WeatherRiskScore}/100 ({weather.WeatherRiskLevel})
- Điểm rủi ro heuristic cuối cùng: {assessment.OverallRiskScore}/100 ({assessment.RiskLevel})
- Độ tin cậy đánh giá: {assessment.AssessmentConfidence}{note}

## Xếp hạng các nguy cơ thiên tai từ dữ liệu thời tiết
{ranking}

## Trigger factors
{triggerFactors}

## Top threats
{threats}

## Potential scenarios from heuristic
{scenarios}

Hãy giải thích dựa trên nguy cơ nổi bật nhất và tham chiếu các nguy cơ khác nếu cần. Đây là đánh giá tham khảo phục vụ vận hành cứu trợ, không phải dự báo khoa học chính thức. Hãy trả JSON đúng schema đã yêu cầu.
""";
        }

        private static string ExtractAssistantContent(JsonElement root)
        {
            if (!root.TryGetProperty("choices", out var choices) || choices.GetArrayLength() == 0)
            {
                throw new InvalidOperationException("LLM response does not contain choices.");
            }

            var message = choices[0].GetProperty("message");
            if (!message.TryGetProperty("content", out var contentElement))
            {
                throw new InvalidOperationException("LLM response does not contain message content.");
            }

            return contentElement.ValueKind switch
            {
                JsonValueKind.String => contentElement.GetString() ?? string.Empty,
                JsonValueKind.Array => string.Concat(contentElement.EnumerateArray()
                    .Where(x => x.TryGetProperty("type", out var type) && type.GetString() == "text")
                    .Select(x => x.TryGetProperty("text", out var text) ? text.GetString() : null)
                    .Where(x => !string.IsNullOrWhiteSpace(x))),
                _ => contentElement.GetRawText()
            };
        }

        private static string ExtractJsonObject(string content)
        {
            var start = content.IndexOf('{');
            var end = content.LastIndexOf('}');

            if (start < 0 || end <= start)
            {
                throw new InvalidOperationException($"LLM did not return valid JSON. Raw content: {content}");
            }

            return content[start..(end + 1)];
        }

        private static string NormalizePath(string? path)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                return "chat/completions";
            }

            return path.TrimStart('/');
        }

        private static JsonSerializerOptions JsonOptions()
        {
            return new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
        }

        private class LlmJsonResponse
        {
            public string? Summary { get; set; }
            public string? DetailedAnalysis { get; set; }
            public List<string>? Recommendations { get; set; }
            public List<string>? PotentialScenarios { get; set; }
        }
    }
}
