// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReliefManagementSystem.Infrastructure.Data;

#nullable disable

namespace ReliefManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303050550_addDonationModProfile")]
    partial class addDonationModProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagedStationReliefStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PicturePublicId")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ManagedStationReliefStationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("AttachmentId");

                    b.HasIndex("RequestId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaRadiusKm")
                        .HasColumnType("double precision");

                    b.Property<decimal>("BudgetSpent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BudgetTotal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByStationId");

                    b.HasIndex("LocationId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignTask", b =>
                {
                    b.Property<Guid>("CampaignTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CampaignTaskId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignTeamId");

                    b.ToTable("CampaignTasks");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignTeam", b =>
                {
                    b.Property<Guid>("CampaignTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("CampaignTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("CampaignId", "TeamId")
                        .IsUnique();

                    b.ToTable("CampaignTeams");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignVehicle", b =>
                {
                    b.Property<Guid>("CampaignVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("CampaignVehicleId");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("VehicleId");

                    b.ToTable("CampaignVehicles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DonatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonorName")
                        .HasColumnType("text");

                    b.Property<Guid?>("DonorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("text");

                    b.HasKey("DonationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DonorUserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReliefStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId");

                    b.HasIndex("ReliefStationId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryStock", b =>
                {
                    b.Property<Guid>("InventoryStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumStockLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplyItemId")
                        .HasColumnType("uuid");

                    b.HasKey("InventoryStockId");

                    b.HasIndex("SupplyItemId");

                    b.HasIndex("InventoryId", "SupplyItemId")
                        .IsUnique();

                    b.ToTable("InventoryStocks");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryTransactionItem", b =>
                {
                    b.Property<Guid>("TransactionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplyItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionItemId");

                    b.HasIndex("SupplyItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("InventoryTransactionItems");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PopulationDensity")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("LocationId");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ManagerProfile", b =>
                {
                    b.Property<Guid>("ManagerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ManagerProfileId");

                    b.HasIndex("AssignedLocationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ManagerProfiles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.MemberTask", b =>
                {
                    b.Property<Guid>("MemberTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubTaskTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskNote")
                        .HasColumnType("text");

                    b.Property<Guid>("VolunteerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("MemberTaskId");

                    b.HasIndex("CampaignTaskId");

                    b.HasIndex("VolunteerProfileId");

                    b.ToTable("MemberTasks");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ModeratorProfile", b =>
                {
                    b.Property<Guid>("ModeratorProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedArea")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ModeratorProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ModeratorProfiles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.PriorityCriteria", b =>
                {
                    b.Property<Guid>("PriorityCriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisasterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Point")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PriorityCriteriaId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PriorityCriterias");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Device")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefNeedItem", b =>
                {
                    b.Property<Guid>("ReliefNeedItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NeedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReliefRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReliefNeedItemId");

                    b.HasIndex("ReliefRequestId");

                    b.ToTable("ReliefNeedItems");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefStation", b =>
                {
                    b.Property<Guid>("ReliefStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentReliefStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReliefStationId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentReliefStationId");

                    b.ToTable("ReliefStations");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefStationTeam", b =>
                {
                    b.Property<Guid>("ReliefStationTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReliefStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ReliefStationTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ReliefStationId", "TeamId")
                        .IsUnique();

                    b.ToTable("ReliefStationTeams");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ReporterFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReporterPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("Requests", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RequestVerification", b =>
                {
                    b.Property<Guid>("RequestVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerifiedBy")
                        .HasColumnType("uuid");

                    b.HasKey("RequestVerificationId");

                    b.HasIndex("RequestId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("RequestVerifications");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueOperation", b =>
                {
                    b.Property<Guid>("RescueOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReliefStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RescueRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("RescueOperationId");

                    b.HasIndex("ReliefStationId");

                    b.HasIndex("RescueRequestId");

                    b.HasIndex("TeamId");

                    b.ToTable("RescueOperations");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueRequestPriority", b =>
                {
                    b.Property<Guid>("RescueRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriorityCriteriaId")
                        .HasColumnType("uuid");

                    b.Property<int>("AppliedPoint")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RescueRequestId", "PriorityCriteriaId");

                    b.HasIndex("PriorityCriteriaId");

                    b.ToTable("RescueRequestPriorities");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyAllocation", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceInventoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("AllocationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("SourceInventoryId");

                    b.ToTable("SupplyAllocations");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyAllocationItem", b =>
                {
                    b.Property<Guid>("AllocationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplyItemId")
                        .HasColumnType("uuid");

                    b.HasKey("AllocationItemId");

                    b.HasIndex("AllocationId");

                    b.HasIndex("SupplyItemId");

                    b.ToTable("SupplyAllocationItems");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyItem", b =>
                {
                    b.Property<Guid>("SupplyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SupplyItemId");

                    b.ToTable("SupplyItems");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TeamId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("ModeratorId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("TeamJoinRequests");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleTeam")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ReliefStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamUsed")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("VehicleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ReliefStationId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VehicleTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerCertificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VolunteerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("CertificateId");

                    b.HasIndex("VolunteerProfileId");

                    b.ToTable("VolunteerCertificates");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerProfile", b =>
                {
                    b.Property<Guid>("VolunteerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("VolunteerProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VolunteerProfiles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerSkill", b =>
                {
                    b.Property<Guid>("VolunteerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolunteerProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("VolunteerSkills");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefRequest", b =>
                {
                    b.HasBaseType("ReliefManagementSystem.Domain.Entities.Request");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CampaignId");

                    b.ToTable("ReliefRequests", (string)null);
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueRequest", b =>
                {
                    b.HasBaseType("ReliefManagementSystem.Domain.Entities.Request");

                    b.Property<string>("DisasterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RescueRequestStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("RescueRequests", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "ManagedStation")
                        .WithMany()
                        .HasForeignKey("ManagedStationReliefStationId");

                    b.Navigation("ManagedStation");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "CreatedByStation")
                        .WithMany()
                        .HasForeignKey("CreatedByStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByStation");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignTask", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Campaign", null)
                        .WithMany("CampaignTasks")
                        .HasForeignKey("CampaignId");

                    b.HasOne("ReliefManagementSystem.Domain.Entities.CampaignTeam", "CampaignTeam")
                        .WithMany()
                        .HasForeignKey("CampaignTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignTeam");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignTeam", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Campaign", "Campaign")
                        .WithMany("CampaignTeams")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Team", "Team")
                        .WithMany("CampaignTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignVehicle", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.VolunteerProfile", "Driver")
                        .WithMany()
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Donation", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Donations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "DonorUser")
                        .WithMany()
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("DonorUser");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "ReliefStation")
                        .WithMany("Inventories")
                        .HasForeignKey("ReliefStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReliefStation");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryStock", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.SupplyItem", "SupplyItem")
                        .WithMany("InventoryItems")
                        .HasForeignKey("SupplyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("SupplyItem");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryTransactionItem", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.SupplyItem", "SupplyItem")
                        .WithMany("InventoryTransactionItems")
                        .HasForeignKey("SupplyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.InventoryTransaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplyItem");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Location", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ManagerProfile", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Location", "AssignedLocation")
                        .WithMany()
                        .HasForeignKey("AssignedLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "User")
                        .WithOne("ManagerProfile")
                        .HasForeignKey("ReliefManagementSystem.Domain.Entities.ManagerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.MemberTask", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.CampaignTask", "CampaignTask")
                        .WithMany("MemberTasks")
                        .HasForeignKey("CampaignTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.VolunteerProfile", "VolunteerProfile")
                        .WithMany()
                        .HasForeignKey("VolunteerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampaignTask");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ModeratorProfile", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "User")
                        .WithOne("ModeratorProfile")
                        .HasForeignKey("ReliefManagementSystem.Domain.Entities.ModeratorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefNeedItem", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefRequest", "ReliefRequest")
                        .WithMany("ReliefNeedItems")
                        .HasForeignKey("ReliefRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReliefRequest");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefStation", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "ParentStation")
                        .WithMany("ChildStations")
                        .HasForeignKey("ParentReliefStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Manager");

                    b.Navigation("ParentStation");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefStationTeam", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "ReliefStation")
                        .WithMany("ReliefStationTeams")
                        .HasForeignKey("ReliefStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReliefStation");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Request", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RequestVerification", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Request", "Request")
                        .WithMany("Verifications")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueOperation", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "ReliefStation")
                        .WithMany()
                        .HasForeignKey("ReliefStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.RescueRequest", "RescueRequest")
                        .WithMany("RescueOperations")
                        .HasForeignKey("RescueRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReliefStation");

                    b.Navigation("RescueRequest");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueRequestPriority", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.PriorityCriteria", "PriorityCriteria")
                        .WithMany("RescueRequestPriorities")
                        .HasForeignKey("PriorityCriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.RescueRequest", "RescueRequest")
                        .WithMany("RescueRequestPriorities")
                        .HasForeignKey("RescueRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriorityCriteria");

                    b.Navigation("RescueRequest");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyAllocation", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Inventory", "SourceInventory")
                        .WithMany()
                        .HasForeignKey("SourceInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("SourceInventory");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyAllocationItem", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.SupplyAllocation", "SupplyAllocation")
                        .WithMany("Items")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.SupplyItem", "SupplyItem")
                        .WithMany("SupplyAllocationItems")
                        .HasForeignKey("SupplyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupplyAllocation");

                    b.Navigation("SupplyItem");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Team", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Team", "Team")
                        .WithMany("TeamJoinRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Team");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.ReliefStation", "ReliefStation")
                        .WithMany("Vehicles")
                        .HasForeignKey("ReliefStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("ReliefStation");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerCertificate", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.VolunteerProfile", "VolunteerProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("VolunteerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerProfile", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.ApplicationUser", "User")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("ReliefManagementSystem.Domain.Entities.VolunteerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerSkill", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Skill", "Skill")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReliefManagementSystem.Domain.Entities.VolunteerProfile", "VolunteerProfile")
                        .WithMany("VolunteerSkills")
                        .HasForeignKey("VolunteerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefRequest", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Campaign", "Campaign")
                        .WithMany("ReliefRequests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReliefManagementSystem.Domain.Entities.Request", null)
                        .WithOne()
                        .HasForeignKey("ReliefManagementSystem.Domain.Entities.ReliefRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueRequest", b =>
                {
                    b.HasOne("ReliefManagementSystem.Domain.Entities.Request", null)
                        .WithOne()
                        .HasForeignKey("ReliefManagementSystem.Domain.Entities.RescueRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ManagerProfile");

                    b.Navigation("ModeratorProfile");

                    b.Navigation("TeamMembers");

                    b.Navigation("VolunteerProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignTasks");

                    b.Navigation("CampaignTeams");

                    b.Navigation("Donations");

                    b.Navigation("ReliefRequests");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.CampaignTask", b =>
                {
                    b.Navigation("MemberTasks");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.PriorityCriteria", b =>
                {
                    b.Navigation("RescueRequestPriorities");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefStation", b =>
                {
                    b.Navigation("ChildStations");

                    b.Navigation("Inventories");

                    b.Navigation("ReliefStationTeams");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Request", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Skill", b =>
                {
                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyAllocation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.SupplyItem", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("InventoryTransactionItems");

                    b.Navigation("SupplyAllocationItems");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.Team", b =>
                {
                    b.Navigation("CampaignTeams");

                    b.Navigation("TeamJoinRequests");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.VolunteerProfile", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("VolunteerSkills");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.ReliefRequest", b =>
                {
                    b.Navigation("ReliefNeedItems");
                });

            modelBuilder.Entity("ReliefManagementSystem.Domain.Entities.RescueRequest", b =>
                {
                    b.Navigation("RescueOperations");

                    b.Navigation("RescueRequestPriorities");
                });
#pragma warning restore 612, 618
        }
    }
}
